image: node:12.0.0
pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm run lint
          - npm run test
  branches:
    develop:
      - step:
          name: Build and test
          script:
          - npm install
          - npm run lint
          - npm run test
      - step:
          name: Deploy develop
          caches:
            - node
          script:
            - pipe: atlassian/aws-sam-deploy:1.2.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: ap-southeast-1
                STACK_NAME: 'aws-sam-example-dev'
                S3_BUCKET: 'sam-example-aws'
                CAPABILITIES: ['CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND']
      - step:
          name: Integration tests
          caches:
            - node
           # - /root/.cache/Cypress
          script:
            - npm install
            - CYPRESS_INSTALL_BINARY=0 npm install
            - touch cypress.env.json
            - echo $CYPRESS_DEV > cypress.env.json
            - npm run e2e
  