image: node:12.0.0
pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm run lint
          - npm run test
  branches:
    develop:
      - step:
          name: Build and test
          script:
          - npm install
          - npm run lint
          - npm run test
      - step:
          name: Deploy develop
          caches:
            - node
          script:
            - CYPRESS_INSTALL_BINARY=0 npm install
            - pipe: atlassian/aws-sam-deploy:1.2.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: ap-southeast-1
                STACK_NAME: 'aws-sam-example-dev'
                S3_BUCKET: 'sam-example-aws'
                CAPABILITIES: ['CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND']

                
  #   - step:
  #      name: Integration tests {develop}
  #      caches: 
  #        - npm
  #        - cypress
  #      image: cypress/browsers:node14.7.0-chrome84
  #        - npm install
  #      script:
  #        - export CYPRESS_api_env=https://tg8e0hnt82.execute-api.ap-southeast-1.amazonaws.com/dev/
  #        - echo "$CYPRESS_api_env"
  #        - export CYPRESS_api_key=$DEV_API_KEY
  #        - export CYPRESS_example_token=$EXAMPLE_TOKEN
  #        - npm run dev-e2e
 