AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Parameters: 
    IdentityNameParameter: 
      Type: String
      Default: aws-sam-example
Resources:
  AwsSamExampleApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: 'aws-sam-example'
      StageName: v1
  helloworld:
    Type: 'AWS::Serverless::Function'
    Properties:
      RestApiId: !Ref AwsSamExampleApiGateway
      Handler: functions/example.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/hello'
            Method: get